name = "screenshoto"
pages_build_output_dir = ".vercel/output/static"
account_id = "e54c8dcb1abbec24d75b5d5471c7c502"

[env.production]
vars = { AI_PROVIDER = "moonshot", AI_MODEL = "moonshot-v1-8k-vision" }
